import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Schkoula</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl text-teal-800">
          Welcome to <a href="https://nextjs.org">Schkoula</a>
        </h1>

        <div className='text-center flex gap-4'>
          <Link href={'app/assignments'} >Assignments</Link>
        </div>
      </main>
    </div>
  )
}
