import Head from 'next/head'
import Link from 'next/link'
import { ExamCalendar } from '../components/exams/exam-calendar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Schkoula</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='min-w-screen min-h-screen mx-auto text-3xl text-slate-800 bg-slate-50 font-poppins'>
          <Head>
            <title>Schkoula</title>
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <div className="flex w-5/6 mx-auto gap-3">
            <ExamCalendar />
          </div>
          
        </div>
      </main>
    </div>
  )
}
